### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by densma1** [EvanPurkhiser/prolink-tools#27] opened 2020-08-20 12:10 UTC
Just curious if overlay supposed to work with this tools? my devices are discovered but ovelay not working. The http url cant be reached. I just see sample overlay display which isnt my content.

**Comment by cottinghamd** [comment] 2020-09-09 07:24
Duplicate of #20

**Comment by EvanPurkhiser** [comment] 2020-10-20 00:12
Going to close this, let me know if you still run into issues @densma1

**Closed by EvanPurkhiser** 2020-10-20 00:12 UTC
