### ISSUE TITLE
Macbook - connected - no cdj info

### ISSUE THREAD

**Issue by Jack-1970** [EvanPurkhiser/prolink-tools#22] opened 2020-08-03 14:10 UTC
Hi there!

I downloaded Prolink on my Macbook Pro (10.14.2). I am using an external Apple firewire network adapter.
Prolink shows "CONNECTED" and show both CDJ-2000nexus (including IP) and the DJM-900nexus and Rekordbox (from an other computer).

But all playing information is empty. So, no BPM, no title, no artist, etc etc.
What can be wrong?

Best regards, Jack

**Comment by MonioDesign** [comment] 2020-10-19 11:39
I had exactly the same issue with the XDJ-XZ but I've just managed to solve it because of something you mentioned that I also use - the apple network adapter.

I think it has something to do with how the Prolink Tools app sets up its virtual CDJ. It seems to _see_ the decks but can't get any information from them and I think that's down to it trying to use the primary network connection - i.e. most probably your wifi and not the ethernet adapter. It detects the devices probably across both networks (wifi and wired) but maybe only listens to data coming in on the primary connection (in this case wifi).

So just to diagnose it I turned off my wifi and hey presto, it all works! If you turn your wifi back on afterwards the app will continue to work for a little while but then stops.

So yeah, you can get it to work you just need to disable wifi. I don't know if there's a way to make the app use just a specific network connection maybe?

**Comment by EvanPurkhiser** [comment] 2020-10-19 11:56
> I don't know if there's a way to make the app use just a specific network connection maybe?

I can add a configuration for this in the future. Right now it does some autodetection magic to pick the adapter

**Comment by MonioDesign** [comment] 2020-10-19 12:56
> I can add a configuration for this in the future. Right now it does some autodetection magic to pick the adapter

Oh yeah, totally understandable - this is just one of those annoying fringe cases although I can't see dongles going away any time soon 😉

Thanks for the work on it though, glad to have figured this out now!

**Comment by VVerdy** [comment] 2020-12-14 20:18
Hello there,
I've just tried today, great stuff thumbs up and thanks for this! :)
I have the same anomaly as Jack-1970. OSX (10.14.2), I've tried with my NXS2 gear.
Happy to help with testing and sharing data in future.

**Comment by EvanPurkhiser** [comment] 2020-12-14 23:41
Got a dongle coming in the mail soon to figure this one out :)

**Comment by EvanPurkhiser** [comment] 2020-12-24 11:33
Wrote up what's going on here in Discord

> So some people using USB network adapters are having problems getting track metadata on macbooks, when using wifi + the dongle specifically
the reason is that, when you just use a dongle the CDJs will self assign IPs
in the range 169.254.0.0/16
which is like, a normal specified thing that anything with an ethernet port will do
the problem is
when we go to broadcast ourselves as a CDJ
we have to broadcast on the broadcast address, which for that subnet would be 169.254.255.255
to announce ourselves so the CDJs recognize us as a CDJ and send more detailed packets
but what happens is
becuase ALL network links cant route 169.254.0.0/16
there are two routes for that
one for the wifi adapter
and one for the usb network adapter
and it will usually route to the wifi one first, so all our announcment packets get broadcast through the wifi link on it's 169.254.0.0/16 subnet
so ofc the CDJs don't see it and don't send us more details (which is why it looks like it never gets track metadata, but yet we still see the CDJs since we receive their broadcasts)
The problem is, I don't really know what the solution is
afaik there's no way to go around the OS's routing table and say 'nono use this specific interface'
you succumb to the will of the OS's routing table
my only real thought is..
I could give an admin prompt and re-order the network routes for them, so it routes to the correct adapter
but it's kinda jank
and route tables get re-configured kinda arbitrarily by the OS
I dunno if this is a problem on windows, the fundamentals are the same so I suspect it would be

**Comment by cottinghamd** [comment] 2020-12-24 13:15
Some testing this evening highlighted the root cause of the issue and the user manual has been updated with information on a fix.

See Troubleshooting -> Check Network Routing

https://www.notion.so/Prolink-Tools-User-Manual-1c0e5b28732b435a9804b992939ed791#eb891bc2fc7e4d92bc4cc7d16f6316e5

The fix is verified on Windows, but not Mac yet. On Mac if you change the network 'Service Order' so that your ProLink connected network interface is at the top of the list, it should resolve the problem. 

Service Order Guide here: 
https://support.apple.com/en-ng/guide/mac-help/mchlp2711/mac

**Comment by EvanPurkhiser** [comment] 2020-12-25 06:18
Going to go ahead and close this issue.

**Closed by EvanPurkhiser** 2020-12-25 06:18 UTC
Labels: bug
